### ISSUE TITLE
expunge the name `slim`, replace with `meta` or `git-meta` where appropriate

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#8]
- [x] rename the repo to `git-meta`
- [x] update docs and read
- [x] change `slm?` to `meta?`, e.g.: `slmc` -> `metac`
